#!/bin/bash

text="boot.txt"

if [ -n "${1}" ]
then
    text=${1}
fi

if [ ! -f "${text}" ]
then
    echo "File ${text} does not exist."
    exit 1
fi

script=${text/.txt/.scr}

if [[ ! -x /usr/bin/mkimage ]]; then
  echo "mkimage not found. Please install uboot-tools:"
  echo "  pacman -S uboot-tools"
  exit 1
fi

mkimage -A arm -O linux -T script -C none -n "U-Boot boot script" -d ${text} ${script}
